import * as abi from '../build/TONBox.abi.json';

const imageBase64 = [
  'te6ccgECHwEABX4AAgE0AwEBAcACAEPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAgAib/APSkICLAAZL0oOGK7VNYMPShCAQBCvSkIPShBQIDzkAHBgBb',
  '32omhp/+mf6YBq6f/p/+n/64W//Df8N3w2/DZ9IH0gGHw1/DU//DD8M3wx/DFABf',
  '/8IWRl//wh54Wf/CNnhYBkfCZ8JvwnfCevGGX/5f/l/+W//CV8Ja8QZ4jnZ2T2qk',
  'AgEgDAkBuv9/jQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE+Gkh',
  '7UTQINdJwgGOKtP/0z/TANXT/9P/0//XC3/4b/hu+G34bPpA+kAw+Gv4an/4Yfhm',
  '+GP4YgoB7I5w9AWNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT4',
  'ao0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABPhrcPhscPhtcPhu',
  'cPhvcAGAQPQO8r3XC//4YnD4Y3D4Zn/4YeLTAAELAKKfgQIA1xgg+QFY+EL5EPKo',
  '3tM/AY4e+EMhuSCfMCD4I4ED6KiCCBt3QKC53pL4Y+CANPI02NMfIcEDIoIQ////',
  '/byxkvI84AHwAfhHbpLyPN4CASAaDQIBIBEOAgFuEA8AdbWNdrf8ILdJeARvaPwk',
  '/CVjgvlwiXwR/CdeeXD6fCf8JWRnwsRnAP0BQDTnoGfA58DkuP2AeAO//DPAAMG1',
  '8CNg/CC3SXgEb2n/6Pwk/CXjgvlwiPwmkLhkEWeF/+SQaHyBEFr/5BDnhf/kmZFo',
  'fIEZENr/mIIvgl15cU18J/wl5GfCxGcA/QFANOegZ8DnwOS4/YAQfDYYeAO//DPA',
  'AgEgExIAv7hlytlaf/ouBC4ZBFnhf/kkGh8gRBa/+QQ54X/5JmRaHyBGRDa/5iCL',
  '4IYmJDgf8cRkehpgP0gGBjkZ8OQZ0AwZ6BnwOfA58mmXK2VEOeF/+S4/YBvGGB/y',
  'XgD7z/8M8AIBIBYUAc22pEWyvhBbpLwCN7RjQhgAAAAAAAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  'AAEcHBw+Er4S/hN+E74T2xVJcD/gFQCGjjUn0NMB+kAwMcjPhyDOgGDPQM+Bz4PI',
  'z5MqRFsqJs8WJc8WJM8L/8gkzwv/I88Lf83NyXH7AN5fBcD/kvAH3n/4ZwEPt1ZD',
  'fb4QW6AXAZSOgN74RvJzcfhm+kD6QZXU0dD6QN/XDX+V1NHQ03/f1w3/ldTR0NP/',
  '39cN/5XU0dDT/9/RJPhqI/hrIvhvIfhtIPhuXwXwB3/4ZxgBaO1E0CDXScIBjirT',
  '/9M/0wDV0//T/9P/1wt/+G/4bvht+Gz6QPpAMPhr+Gp/+GH4Zvhj+GIZAOaOcPQF',
  'jQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE+GqNCGAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT4a3D4bHD4bXD4bnD4b3ABgED0DvK9',
  '1wv/+GJw+GNw+GZ/+GHiAgEgHBsAe7vOLDWNFwcDB4MSHA/44jI9DTAfpAMDHIz4',
  'cgzoBgz0DPgc+Bz5Lziw1iIc8L/8lx+wDeMMD/kvAH3n/4Z4AgEgHh0Ah7lluOG/',
  'CC3SXgEb2i4fCYYkOB/xxGR6GmA/SAYGORnw5BnQDBnoGfA58DnyTZbjhsQ54X/5',
  'Lj9gG8YYH/JeAPvP/wzwAHLccCLQ1gIx0gD6QDD4adwhxwCQ4CHXDR+S8jzhUxGQ',
  '4cEDIoIQ/////byxkvI84AHwAfhHbpLyPN4=',
].join('');

export default {
  abi,
  imageBase64,
}
